apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deploy
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:           
      containers:
      - name: identityapi
        image: azuredeveloper/identityapi:latest        
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__IdentityConnection
          value: "Data Source=mssql;Initial Catalog=IdentityDB;Persist Security Info=True;User ID=sa;Password=Password@123"
        - name: Jwt__Secret
          value: "thisismylengthykeyforencryption"
        - name: Jwt__Issuer
          value: "http://identitysvc"
        - name: Jwt__Audience
          value: "http://eventsvc"
